name: Validate issue

on:
  issues:
    types: 
      - opened

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUMBER: ${{ github.event.issue.number }}
  REPO: "divineniiquaye/uniwind"

jobs:
  autoclose:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check for valid reproduction
        id: check
        env:
          BODY: ${{ github.event.issue.body }}
        run: |
          if echo "$BODY" | grep -qP "github\.com(?!\/uni-stack)"; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi
      - name: Close Issue
        if: steps.check.outputs.valid == 'false'
        run: gh issue close "$NUMBER" --comment "This issue has been automatically closed because it **lacks a clear, minimal reproduction** that we can use to verify the reported bug." --repo "$REPO"
      - name: Label Issue
        if: steps.check.outputs.valid == 'false'
        run: gh issue edit "$NUMBER" --add-label "repro-required" --repo "$REPO"
